public class HistoricalEvents {
  public static HistoricalEvent[] events = new HistoricalEvent[] {
    new HistoricalEvent ("Narodziny Jezusa", 1),
    new HistoricalEvent ("Koniec staro¿ytnoœci", 476),
    new HistoricalEvent ("Pocz¹tek œredniowiecza", 476),
    new HistoricalEvent ("Narodziny Mieszka I", 930),
    new HistoricalEvent ("Pocz¹tek panowania Mieszka I", 960),
    new HistoricalEvent ("Ma³¿eñstwo Mieszka I z Dobraw¹", 966),
    new HistoricalEvent ("Narodziny Boles³awa I Chrobrego", 967),
    new HistoricalEvent ("Chrzest Polski", 966),
    new HistoricalEvent ("Narodziny Mieszka II Lamberta", 990),
    new HistoricalEvent ("Œmieræ Mieszka I", 992),
    new HistoricalEvent ("Koronacja Boles³awa  I Chrobrego", 1025),
    new HistoricalEvent ("Œmieræ Boles³awa Chrobrego", 1025),
    new HistoricalEvent ("Koronacja Mieszka II Lamberta", 1025),
    new HistoricalEvent ("Œmieræ Mieszka II Lamberta", 1034),
    new HistoricalEvent ("Narodziny Ludwika I Wêgierskiego", 1326),
    new HistoricalEvent ("Narodziny W³adys³awa II Jagie³³y", 1362),
    new HistoricalEvent ("Koronacja Ludwika I Wêgierskiego", 1370),
    new HistoricalEvent ("Œmieræ Ludwika I Wêgierskiego", 1382),
    new HistoricalEvent ("Narodziny Jadwigi I Andegaweñskiej", 1373),
    new HistoricalEvent ("Koronacja Jadwigi I Andegaweñskiej", 1384),
    new HistoricalEvent ("Zawarcie unii w Krewie", 1385),
    new HistoricalEvent ("Koronacja W³adys³awa II Jagie³³y", 1386),
    new HistoricalEvent ("Œmieræ Jadwigi I Andegaweñskiej", 1399),
    new HistoricalEvent ("Bitwa pod Grunwaldem", 1410),
    new HistoricalEvent ("Narodziny W³adys³awa III Warneñczyka", 1424),
    new HistoricalEvent ("Narodziny Kazimierza IV Jagielloñczyka", 1427),
    new HistoricalEvent ("Œmieræ W³adys³awa II Jagie³³y", 1434),
    new HistoricalEvent ("Koronacja W³adys³awa III Warneñczyka", 1434),
    new HistoricalEvent ("Œmieræ W³adys³awa III Warneñczyka", 1444),
    new HistoricalEvent ("Koronacja Kazimierza IV Jagielloñczyka", 1447),
    new HistoricalEvent ("Narodziny Jana I Olbrachta", 1459),
    new HistoricalEvent ("Narodziny Aleksandra I Jagielloñczyka", 1461),
    new HistoricalEvent ("Narodziny Zygmunta I Starego", 1467),
    new HistoricalEvent ("Koniec œredniowiecza", 1492),
    new HistoricalEvent ("Pocz¹tek nowo¿ytnoœci", 1492),
    new HistoricalEvent ("Œmieræ Kazimierza IV Jagielloñczyka", 1492),
    new HistoricalEvent ("Koronacja Jana I Olbrachta", 1492),
    new HistoricalEvent ("Œmieræ Jana I Olbrachta", 1501),
    new HistoricalEvent ("Koronacja Aleksandra I Jagielloñczyka", 1501),
    new HistoricalEvent ("Œmieræ Aleksandra I Jagielloñczyka", 1506),
    new HistoricalEvent ("Koronacja Zygmunta I Starego", 1507),
    new HistoricalEvent ("Narodziny Zygmunta II Augusta", 1520),
    new HistoricalEvent ("Koronacja Zygmunta II Augusta", 1530),
    new HistoricalEvent ("Œmieræ Zygmunta I Starego", 1548),
    new HistoricalEvent ("Œmieræ Zygmunta II Augusta", 1572),
    new HistoricalEvent ("Pierwszy rozbiór Polski", 1772),
    new HistoricalEvent ("Drugi rozbiór Polski", 1793),
    new HistoricalEvent ("Insurekcja koœciuszkowska", 1794),
    new HistoricalEvent ("Utworzenie Legionów Polskich", 1795),
    new HistoricalEvent ("Narodziny Adama Mickiewicza", 1798),
    new HistoricalEvent ("Narodziny Juliusza S³owackiego", 1809),
    new HistoricalEvent ("Narodziny Fryderyka Chopina", 1810),
    new HistoricalEvent ("Narodziny Zygmunta Krasiñskiego", 1812),
    new HistoricalEvent ("Wybuch powstania listopadowego", 1830),
    new HistoricalEvent ("Klêska powstania listopadowego", 1831),
    new HistoricalEvent ("Wydanie \"Pana Tadeusza\"", 1834),
    new HistoricalEvent ("Wydanie \"Balladyny\"", 1834),
    new HistoricalEvent ("Powstanie krakowskie", 1846),
    new HistoricalEvent ("Œmieræ Juliusza S³owackiego", 1849),
    new HistoricalEvent ("Œmieræ Adama Mickiewicza", 1855),
    new HistoricalEvent ("Œmieræ Zygmunta Krasiñskiego", 1859),
    new HistoricalEvent ("Wybuch powstania styczniowego", 1863),
    new HistoricalEvent ("Klêska powstania styczniowego", 1864),
    new HistoricalEvent ("Pocz¹tek I wojny œwiatowej", 1914),
    new HistoricalEvent ("Koniec nowo¿ytnoœci", 1914),
    new HistoricalEvent ("Pocz¹tek wspó³czesnoœci", 1914),
    new HistoricalEvent ("Koniec I wojny œwiatowej", 1918),
    new HistoricalEvent ("Traktat wersalski", 1919),
    new HistoricalEvent ("I powstanie œl¹skie", 1919),
    new HistoricalEvent ("II powstanie œl¹skie", 1920),
    new HistoricalEvent ("III powstanie œl¹skie", 1921),
    new HistoricalEvent ("Utworzenie Zwi¹zku Radzieckiego", 1922),
    new HistoricalEvent ("Pocz¹tek II wojny œwiatowej", 1939),
    new HistoricalEvent ("Utworzenie AK", 1942),
    new HistoricalEvent ("Utworzenie PKWN", 1944),
    new HistoricalEvent ("Powstanie Warszawskie", 1944),
    new HistoricalEvent ("Koniec II wojny œwiatowej", 1945),
    new HistoricalEvent ("Odzyskanie niepodleglosci", 1918),
    new HistoricalEvent ("Powo³anie RWPG", 1949),
    new HistoricalEvent ("Przyjêcie konstytucji PRL", 1952),
    new HistoricalEvent ("Œmieræ Józefa Stalina", 1953),
    new HistoricalEvent ("Utworzenie Uk³adu Warszawskiego", 1955),
    new HistoricalEvent ("Pocz¹tek rz¹dów W³adys³awa Gomu³ki", 1956),
    new HistoricalEvent ("Koniec rzadów W³adys³awa Gomu³ki", 1970),
    new HistoricalEvent ("Pocz¹tek rz¹dów Edwarda Gierka", 1970),
    new HistoricalEvent ("Koniec rz¹dów Edwarda Gierka", 1980),
    new HistoricalEvent ("Wprowadzenie stanu wojennego w PRL", 1981),
    new HistoricalEvent ("Zniesienie stanu wojennego w PRL", 1983),
    new HistoricalEvent ("Obrady Okr¹g³ego Sto³u", 1989),
    new HistoricalEvent ("Samorozwi¹zanie PZPR", 1990),
    new HistoricalEvent ("Rozpad Zwi¹zku Radzickiego", 1991),
    new HistoricalEvent ("Opuszczenie Polski przez wojska rosyjskie", 1993),
    new HistoricalEvent ("Denominacja z³otówki", 1995),
    new HistoricalEvent ("Przyst¹pienie Polski do NATO", 1999),
    new HistoricalEvent ("Œmieræ Jan Paw³a II", 2005),
    new HistoricalEvent ("Przyst¹pienie Polski do UE", 2004)
  };
}