public class GeographicalDatabase {
  public static GeographicalRecord[] records = new GeographicalRecord[] {
    new GeographicalRecord ("Polska", "Warszawa"),
    new GeographicalRecord ("Litwa", "Wilno"),
    new GeographicalRecord ("£otwa", "Ryga"),
    new GeographicalRecord ("Estonia", "Tallinn"),
    new GeographicalRecord ("Bia³oruœ", "Miñsk"),
    new GeographicalRecord ("Ukraina", "Kijów"),
    new GeographicalRecord ("Rumunia", "Bukareszt"),
    new GeographicalRecord ("Mo³dawia", "Kiszyniów"),
    new GeographicalRecord ("S³owacja", "Bratys³awa"),
    new GeographicalRecord ("Czechy", "Praga"),
    new GeographicalRecord ("Niemcy", "Berlin"),
    new GeographicalRecord ("Austria", "Wiedeñ"),
    new GeographicalRecord ("Wêgry", "Budapeszt"),
    new GeographicalRecord ("Belgia", "Bruksela"),
    new GeographicalRecord ("Holandia", "Amsterdam"),
    new GeographicalRecord ("Francja", "Pary¿"),
    new GeographicalRecord ("W³ochy", "Rzym"),
    new GeographicalRecord ("Hiszpania", "Madryt"),
    new GeographicalRecord ("Portugalia", "Lizbona"),
    new GeographicalRecord ("Norwegia", "Oslo"),
    new GeographicalRecord ("Szwecja", "Sztokholm"),
    new GeographicalRecord ("Finlandia", "Helsinki"),
    new GeographicalRecord ("Anglia", "Londyn"),
    new GeographicalRecord ("Irlandia", "Dublin"),
    new GeographicalRecord ("Islandia", "Reykjavik"),
    new GeographicalRecord ("S³owenia", "Lublana"),
    new GeographicalRecord ("Chorwacja", "Zagrzeb"),
    new GeographicalRecord ("Boœnia i Hercegowina", "Sarajewo"),
    new GeographicalRecord ("Serbia", "Belgrad"),
    new GeographicalRecord ("Czarnogóra", "Podgorica"),
    new GeographicalRecord ("Kosowo", "Prisztina"),
    new GeographicalRecord ("Albiania", "Tirana"),
    new GeographicalRecord ("Macedonia", "Skopje"),
    new GeographicalRecord ("Grecja", "Ateny"),
    new GeographicalRecord ("Bu³garia", "Sofia"),
    new GeographicalRecord ("Dania", "Kopenhaga"),
    new GeographicalRecord ("Andora", "Andora"),
    new GeographicalRecord ("Liechtenstein", "Vaduz"),
    new GeographicalRecord ("Luksemburg", "Luksemburg"),
    new GeographicalRecord ("Malta", "Valetta"),
    new GeographicalRecord ("Monako", "Monako"),
    new GeographicalRecord ("San Marino", "San Marino"),
    new GeographicalRecord ("Watykan", "Watykan"),
    new GeographicalRecord ("Rosja", "Moskwa") /* FUJ! */
  };
}